name: golden_layout
description: A internal window library for Flutter based on http://golden-layout.com/
version: 0.0.3
author: Rody Davis <rody.davis.jr@gmail.com>
maintainer: Rody Davis (@rodydavis)
homepage: https://github.com/rodydavis/golden_layout

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0

flutter:
